### ISSUE TITLE
YAML error: found character that cannot start any token

### ISSUE THREAD

**Issue by stephanos** [moraes/config#1]
Maybe I'm doing something wrong, but when I parse this file:

```
smtp:
    port: 25
    host: smtp.mail.com
    username: johndoe
    password: secretpassword
```

with

```
config.ParseYaml(configData)
```

I get 

```
YAML error: line 1: found character that cannot start any token
```
